/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.vo;

/**
 * The documentation of the class ProjectTechnologyVo.
 *
 * @author 
 * @generated 
 */
public class ProjectTechnologyVO {

    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public ProjectTechnologyVO() {
        super();
    }

    // Start of user code For declaring your own attributes and operations for ProjectTechnologyVo
    // TODO should be implemented
    // any more comments

    //private List<ProjectVO> projectList ;

    /** The technology stack vo. */
    private TechnologyStackVO technologyStackVO;

    /** The project count. */
    private Integer projectCount;

    /**
     * Gets the project count.
     *
     * @return the project count
     */
    public Integer getProjectCount() {
        return projectCount;
    }

    /**
     * Sets the project count.
     *
     * @param projectCount the new project count
     */
    public void setProjectCount(Integer projectCount) {
        this.projectCount = projectCount;
    }

    /**
     * Gets the technology stack vo.
     *
     * @return the technology stack vo
     */
    public TechnologyStackVO getTechnologyStackVO() {
        return technologyStackVO;
    }

    /**
     * Sets the technology stack vo.
     *
     * @param technologyStackVO the new technology stack vo
     */
    public void setTechnologyStackVO(TechnologyStackVO technologyStackVO) {
        this.technologyStackVO = technologyStackVO;
    }

    // End of user code

}
