/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.vo;

/**
 * The documentation of the class ProjectTechCategoryVO.
 *
 * @author 
 * @generated 
 */
public class ProjectTechCategoryVO {

    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public ProjectTechCategoryVO() {
        super();
    }

    // Start of user code For declaring your own attributes and operations for ProjectTechCategoryVO
    // TODO should be implemented
    // any more comments
    // private List<ProjectVO> projectList ;

    /** The project count. */
    private Double projectCount;

    /** The technology category vo. */
    private TechnologyCategoryVO technologyCategoryVO;

    /**
     * Gets the project count.
     *
     * @return the project count
     */
    public Double getProjectCount() {
        return projectCount;
    }

    /**
     * Sets the project count.
     *
     * @param projectCount the new project count
     */
    public void setProjectCount(Double projectCount) {
        this.projectCount = projectCount;
    }

    /**
     * Gets the technology category vo.
     *
     * @return the technology category vo
     */
    public TechnologyCategoryVO getTechnologyCategoryVO() {
        return technologyCategoryVO;
    }

    /**
     * Sets the technology category vo.
     *
     * @param technologyCategoryVO the new technology category vo
     */
    public void setTechnologyCategoryVO(TechnologyCategoryVO technologyCategoryVO) {
        this.technologyCategoryVO = technologyCategoryVO;
    }

    // End of user code

}
