/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.vo;

import java.util.List;

/**
 * The documentation of the class SearchResultVO.
 *
 * @author 
 * @generated 
 */
public class SearchResultVO {

    /** The search project result v os. */
    private List<SearchProjectResultVO> searchProjectResultVOs;

    /** The total count. */
    private int totalCount;

    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public SearchResultVO() {
        super();
    }

    /**
     * Gets the search project result v os.
     *
     * @return the search project result v os
     */
    public List<SearchProjectResultVO> getSearchProjectResultVOs() {
        return searchProjectResultVOs;
    }

    /**
     * Sets the search project result v os.
     *
     * @param searchProjectResultVOs the new search project result v os
     */
    public void setSearchProjectResultVOs(List<SearchProjectResultVO> searchProjectResultVOs) {
        this.searchProjectResultVOs = searchProjectResultVOs;
    }

    /**
     * Gets the total count.
     *
     * @return the total count
     */
    public int getTotalCount() {
        return totalCount;
    }

    /**
     * Sets the total count.
     *
     * @param totalCount the new total count
     */
    public void setTotalCount(int totalCount) {
        this.totalCount = totalCount;
    }

}
