/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.vo;

/**
 * The documentation of the class SearchResultVO.
 *
 * @author 
 * @generated 
 */
public class SummaryVO {

    /** The total projects. */
    private Long totalProjects;

    /** The total technology categories. */
    private Long totalTechnologyCategories;

    /** The total technologies. */
    private Long totalTechnologies;

    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public SummaryVO() {
        super();
    }

    /**
     * Gets the total projects.
     *
     * @return the total projects
     */
    public Long getTotalProjects() {
        return totalProjects;
    }

    /**
     * Sets the total projects.
     *
     * @param totalProjects the new total projects
     */
    public void setTotalProjects(Long totalProjects) {
        this.totalProjects = totalProjects;
    }

    /**
     * Gets the total technology categories.
     *
     * @return the total technology categories
     */
    public Long getTotalTechnologyCategories() {
        return totalTechnologyCategories;
    }

    /**
     * Sets the total technology categories.
     *
     * @param totalTechnologyCategories the new total technology categories
     */
    public void setTotalTechnologyCategories(Long totalTechnologyCategories) {
        this.totalTechnologyCategories = totalTechnologyCategories;
    }

    /**
     * Gets the total technologies.
     *
     * @return the total technologies
     */
    public Long getTotalTechnologies() {
        return totalTechnologies;
    }

    /**
     * Sets the total technologies.
     *
     * @param totalTechnologies the new total technologies
     */
    public void setTotalTechnologies(Long totalTechnologies) {
        this.totalTechnologies = totalTechnologies;
    }

}
