/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.vo;

/**
 * The documentation of the class TechnologyCategoryVO.
 *
 * @author 
 * @generated 
 */

public class TechnologyCategoryVO {

    /** The technology category id. */
    private Integer technologyCategoryId;

    /** The cat name. */
    private String catName;

    /** The version. */
    private int version = 0;

    /**
     * Gets the technology category id.
     *
     * @return the technology category id
     */
    public Integer getTechnologyCategoryId() {
        return technologyCategoryId;
    }

    /**
     * Sets the technology category id.
     *
     * @param technologyCategoryId the new technology category id
     */
    public void setTechnologyCategoryId(Integer technologyCategoryId) {
        this.technologyCategoryId = technologyCategoryId;
    }

    /**
     * Gets the cat name.
     *
     * @return the cat name
     */
    public String getCatName() {
        return catName;
    }

    /**
     * Sets the cat name.
     *
     * @param catName the new cat name
     */
    public void setCatName(String catName) {
        this.catName = catName;
    }

    /**
     * Gets the version.
     *
     * @return the version
     */
    public int getVersion() {
        return version;
    }

    /**
     * Sets the version.
     *
     * @param version the new version
     */
    public void setVersion(int version) {
        this.version = version;
    }

    /**
     * 
     */
    public TechnologyCategoryVO() {
        super();
    }

    /**
     * @param technologyCategoryId
     * @param catName
     */
    public TechnologyCategoryVO(Integer technologyCategoryId, String catName) {
        super();
        this.technologyCategoryId = technologyCategoryId;
        this.catName = catName;
    }

}
