/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service.business;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

/**
 * The documentation of the class TechnologyServiceBLTest
 * 
 * @author
 * @generated
 */

public class TechnologyServiceBLTest {

    // Start of user code For declaring your own attributes for TechnologyService
    // add addtional attributes/fields here
    // any more comments

    // End of user code
    /**
     * The documentation of the method retrieveTechnologybyKeywordTest.
     * 
     * 
     * @generated
     */
    /**
     * *
     */
    @Test
    public void retrieveTechnologybyKeywordTest() {
        // Start of user code for the body of retrieveTechnologybyKeyword
        // TODO should be implemented
        // any more comments

        // End of user code
    }

    // Start of user code For declaring your own operations for TechnologyService
    // add addtional operations here
    // any more comments

    // End of user code
    /**
     * The documentation of the method setUpBeforeClass
     */
    @BeforeClass
    public static void setUpBeforeClass() throws Exception {
        // Start of user code for the body of setUpBeforeClass
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method tearDownAfterClass
     */
    @AfterClass
    public static void tearDownAfterClass() throws Exception {
        // Start of user code for the body of tearDownAfterClass
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method setUp
     */
    @Before
    public void setUp() throws Exception {
        // Start of user code for the body of setUp
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method tearDown
     */
    @After
    public void tearDown() throws Exception {
        // Start of user code for the body of tearDown
        // TODO should be implemented
        // any more comments
        // End of user code
    }
}
