/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.persistence;

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import com.dell.coe.pts.common.dao.AuditVersionEntity;
import com.dell.coe.pts.common.dao.PersistentEntity;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * The documentation of the class TechnologyStack
 * 
 * @author
 * @generated
 */
@Entity
@Table(name = "TECHNOLOGY_STACK")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "technologyStackId")
public class TechnologyStack extends AuditVersionEntity implements PersistentEntity {

    private static final long serialVersionUID = -7934657200872524919L;

    @Id
    @GeneratedValue(generator = "TECHNOLOGY_STACK_GEN")
    @SequenceGenerator(name = "TECHNOLOGY_STACK_GEN", sequenceName = "TECHNOLOGY_STACK_SEQ")
    @Column(name = "TECHNOLOGY_STACK_ID")
    // TECHNOLOGY_STACK_ID
    private Integer technologyStackId;

    /**
     * The documentation of the getter getTechnologyStackId.
     * 
     * @generated
     */
    public Integer getTechnologyStackId() {
        return this.technologyStackId;
    }

    /**
     * The documentation of the setter setTechnologyStackId.
     * 
     * @generated
     */
    public void setTechnologyStackId(Integer technologyStackId) {
        this.technologyStackId = technologyStackId;
    }

    /**
     * The documentation of the attribute project.
     * 
     * @generated
     */

    @ManyToMany(cascade = CascadeType.ALL, mappedBy = "technologystack")
    @LazyCollection(LazyCollectionOption.FALSE)
    private Set<Project> project;

    /**
     * The documentation of the attribute technologycategory.
     * 
     * @generated
     */

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TECHNOLOGY_CATEGORY_ID")
    private TechnologyCategory technologycategory;
    /**
     * The documentation of the attribute techName.
     * 
     * @generated
     */
    @Column(name = "TECH_NAME")
    private String techName;
    /**
     * The documentation of the attribute techVersion.
     * 
     * @generated
     */
    @Column(name = "TECH_VERSION")
    private String techVersion;

    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public TechnologyStack() {
        super();
    }

    // Start of user code For declaring your own attributes and operations for TechnologyStack
    // TODO should be implemented
    // any more comments

    // End of user code

    /**
     * The documentation of the getter getProject.
     * 
     * @generated
     */
    public Set<Project> getProject() {
        return this.project;
    }

    /**
     * The documentation of the setter setProject.
     * 
     * @generated
     */
    public void setProject(Set<Project> newProject) {
        this.project = newProject;
    }

    /**
     * The documentation of the getter getTechnologycategory.
     * 
     * @generated
     */
    public TechnologyCategory getTechnologycategory() {
        return this.technologycategory;
    }

    /**
     * The documentation of the setter setTechnologycategory.
     * 
     * @generated
     */
    public void setTechnologycategory(TechnologyCategory newTechnologycategory) {
        this.technologycategory = newTechnologycategory;
    }

    /**
     * The documentation of the getter getTechName.
     * 
     * @generated
     */
    public String getTechName() {
        return this.techName;
    }

    /**
     * The documentation of the setter setTechName.
     * 
     * @generated
     */
    public void setTechName(String newTechName) {
        this.techName = newTechName;
    }

    /**
     * The documentation of the getter getTechVersion.
     * 
     * @generated
     */
    public String getTechVersion() {
        return this.techVersion;
    }

    /**
     * The documentation of the setter setTechVersion.
     * 
     * @generated
     */
    public void setTechVersion(String newTechVersion) {
        this.techVersion = newTechVersion;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((techName == null) ? 0 : techName.hashCode());
        result = prime * result + ((techVersion == null) ? 0 : techVersion.hashCode());
        result = prime * result + ((technologyStackId == null) ? 0 : technologyStackId.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!super.equals(obj))
            return false;
        if (getClass() != obj.getClass())
            return false;
        TechnologyStack other = (TechnologyStack) obj;
        if (techName == null) {
            if (other.techName != null)
                return false;
        } else if (!techName.equals(other.techName))
            return false;
        if (techVersion == null) {
            if (other.techVersion != null)
                return false;
        } else if (!techVersion.equals(other.techVersion))
            return false;
        if (technologyStackId == null) {
            if (other.technologyStackId != null)
                return false;
        } else if (!technologyStackId.equals(other.technologyStackId))
            return false;
        return true;
    }

    /**
     * The documentation of the method toString().
     * 
     * @generated
     */
    @Override
    public String toString() {
        StringBuilder retValue = new StringBuilder();
        retValue.append("TechnologyStack [ ");
        if (project != null) {
            retValue.append(" project = ");
            retValue.append(project.toString());
        }
        if (technologycategory != null) {
            retValue.append(" technologycategory = ");
            retValue.append(technologycategory.toString());
        }
        if (techName != null) {
            retValue.append(" techName = ");
            retValue.append(techName);
        }
        if (techVersion != null) {
            retValue.append(" techVersion = ");
            retValue.append(techVersion);
        }
        if (technologyStackId != null) {
            retValue.append(" technologyStackId = ");
            retValue.append(technologyStackId.toString());
        }
        retValue.append(" ] ");
        return retValue.toString();
    }
}
