/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.persistence;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.dell.coe.pts.common.dao.AuditVersionEntity;
import com.dell.coe.pts.common.dao.PersistentEntity;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * The documentation of the class TechnologyCategory
 * 
 * @author
 * @generated
 */
@Entity
@Table(name = "TECHNOLOGY_CATEGORY")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "technologyCategoryId")
public class TechnologyCategory extends AuditVersionEntity implements PersistentEntity, Comparable<TechnologyCategory> {

    private static final long serialVersionUID = 2096847203603569132L;

    @Id
    @GeneratedValue(generator = "TECHNOLOGY_CATEGORY_GEN")
    @SequenceGenerator(name = "TECHNOLOGY_CATEGORY_GEN", sequenceName = "TECHNOLOGY_CATEGORY_SEQ")
    @Column(name = "TECHNOLOGY_CATEGORY_ID")
    // TECHNOLOGY_CATEGORY_ID
    private Integer technologyCategoryId;

    /**
     * The documentation of the getter getTechnologyCategoryId.
     * 
     * @generated
     */
    public Integer getTechnologyCategoryId() {
        return this.technologyCategoryId;
    }

    /**
     * The documentation of the setter setTechnologyCategoryId.
     * 
     * @generated
     */
    public void setTechnologyCategoryId(Integer technologyCategoryId) {
        this.technologyCategoryId = technologyCategoryId;
    }

    /**
     * The documentation of the attribute catName.
     * 
     * @generated
     */
    @Column(name = "CAT_NAME", unique = true, nullable = false)
    private String catName;

    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public TechnologyCategory() {
        super();
    }

    // Start of user code For declaring your own attributes and operations for TechnologyCategory
    // TODO should be implemented
    // any more comments

    // End of user code

    /**
     * The documentation of the getter getCatName.
     * 
     * @generated
     */
    public String getCatName() {
        return this.catName;
    }

    /**
     * The documentation of the setter setCatName.
     * 
     * @generated
     */
    public void setCatName(String newCatName) {
        this.catName = newCatName;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = super.hashCode();
        result = prime * result + ((catName == null) ? 0 : catName.hashCode());
        result = prime * result + ((technologyCategoryId == null) ? 0 : technologyCategoryId.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!super.equals(obj))
            return false;
        if (getClass() != obj.getClass())
            return false;
        TechnologyCategory other = (TechnologyCategory) obj;
        if (catName == null) {
            if (other.catName != null)
                return false;
        } else if (!catName.equals(other.catName))
            return false;
        if (technologyCategoryId == null) {
            if (other.technologyCategoryId != null)
                return false;
        } else if (!technologyCategoryId.equals(other.technologyCategoryId))
            return false;
        return true;
    }

    /**
     * The documentation of the method toString().
     * 
     * @generated
     */
    @Override
    public String toString() {
        StringBuilder retValue = new StringBuilder();
        retValue.append("TechnologyCategory [ ");
        if (catName != null) {
            retValue.append(" catName = ");
            retValue.append(catName);
        }
        if (technologyCategoryId != null) {
            retValue.append(" technologyCategoryId = ");
            retValue.append(technologyCategoryId.toString());
        }
        retValue.append(" ] ");
        return retValue.toString();
    }

    @Override
    public int compareTo(TechnologyCategory arg0) {
        return this.getCatName().compareTo(arg0.getCatName());
    }
}
