/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.technicalservice;

import java.util.List;

import com.dell.coe.pts.vo.ProjectVO;
import com.dell.coe.virtuoso.common.service.AbstractService;

/**
 * The documentation of the interface ProjectSerivce.
 *
 * @author 
 * @generated 
 */
public interface ProjectTechnicalService extends AbstractService {

    /**
     * Creates the project.
     *
     * @param project the project
     * @return the project vo
     */
    ProjectVO createProject(ProjectVO project);

    /**
     * Update project.
     *
     * @param project the project
     * @return the project vo
     */
    ProjectVO updateProject(ProjectVO project);

    /**
     * Gets the project by id.
     *
     * @param id the id
     * @return the project by id
     */
    ProjectVO getProjectById(Integer id);

    /**
     * Gets the all project.
     *
     * @return the all project
     */
    List<ProjectVO> getAllProject();

    /**
     * Removes the project.
     *
     * @param project the project
     */
    void removeProject(ProjectVO project);
}
