/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.technicalservice;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;

import com.dell.coe.pts.technicalservice.business.ProjectTechnicalBL;
import com.dell.coe.pts.vo.ProjectVO;
import com.dell.coe.virtuoso.common.service.AbstractServiceImpl;

/**
 * The documentation of the class ProjectTechnicalRestServiceImpl.
 *
 * @author
 * @generated
 */
@Path("/project")
public class ProjectTechnicalRestServiceImpl extends AbstractServiceImpl implements ProjectTechnicalService {

    /** The project technical bl. */
    @Autowired
    private ProjectTechnicalBL projectTechnicalBL;

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.dell.coe.pts.technicalservice.ProjectTechnicalService#createProject
     * (com.dell.coe.pts.vo.ProjectVO)
     */
    @Override
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Path("/createProject")
    public ProjectVO createProject(@RequestBody ProjectVO project) {
        return projectTechnicalBL.createProject(project);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.dell.coe.pts.technicalservice.ProjectTechnicalService#updateProject
     * (com.dell.coe.pts.vo.ProjectVO)
     */
    @Override
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Path("/updateProject")
    public ProjectVO updateProject(@RequestBody ProjectVO project) {
        return projectTechnicalBL.updateProject(project);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.dell.coe.pts.technicalservice.ProjectTechnicalService#getProjectById
     * (java.lang.Integer)
     */
    @Override
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Path("/getProjectById/{id}")
    public ProjectVO getProjectById(@PathParam("id") Integer id) {
        return projectTechnicalBL.getProjectById(id);
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.dell.coe.pts.technicalservice.ProjectTechnicalService#getAllProject()
     */
    @Override
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("/getAllProject")
    public List<ProjectVO> getAllProject() {
        return projectTechnicalBL.getAllProject();
    }

    /*
     * (non-Javadoc)
     * 
     * @see
     * com.dell.coe.pts.technicalservice.ProjectTechnicalService#removeProject
     * (com.dell.coe.pts.vo.ProjectVO)
     */
    @Override
    @DELETE
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Path("/removeProject")
    public void removeProject(@RequestBody ProjectVO project) {
        projectTechnicalBL.removeProject(project);
    }
}
