/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.technicalservice;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;

import com.dell.coe.pts.technicalservice.business.TechnologyStackTechnicalBL;
import com.dell.coe.pts.vo.TechCategoryReportVO;
import com.dell.coe.pts.vo.TechnologyStackVO;
import com.dell.coe.virtuoso.common.service.AbstractServiceImpl;

/**
 * The documentation of the class TechnologyStackTechnicalRestServiceImpl.
 *
 * @author 
 * @generated 
 */
@Path("/technologystack")
public class TechnologyStackTechnicalRestServiceImpl extends AbstractServiceImpl implements TechnologyStackTechnicalService {

    /** The technology stack technical bl. */
    @Autowired
    private TechnologyStackTechnicalBL technologyStackTechnicalBL;

    /* (non-Javadoc)
     * @see com.dell.coe.pts.technicalservice.TechnologyStackTechnicalService#createTechnologyStack(com.dell.coe.pts.vo.TechnologyStackVO)
     */
    @Override
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Path("/createTechnologyStack")
    public TechnologyStackVO createTechnologyStack(@RequestBody TechnologyStackVO technologystack) {
        return technologyStackTechnicalBL.createTechnologyStack(technologystack);
    }

    /* (non-Javadoc)
     * @see com.dell.coe.pts.technicalservice.TechnologyStackTechnicalService#updateTechnologyStack(com.dell.coe.pts.vo.TechnologyStackVO)
     */
    @Override
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Path("/updateTechnologyStack")
    public TechnologyStackVO updateTechnologyStack(@RequestBody TechnologyStackVO technologystack) {
        return technologyStackTechnicalBL.updateTechnologyStack(technologystack);
    }

    /* (non-Javadoc)
     * @see com.dell.coe.pts.technicalservice.TechnologyStackTechnicalService#getTechnologyStackById(java.lang.Integer)
     */
    @Override
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Path("/getTechnologyStackById/{id}")
    public TechnologyStackVO getTechnologyStackById(@PathParam("id") Integer id) {
        return technologyStackTechnicalBL.getTechnologyStackById(id);
    }

    /* (non-Javadoc)
     * @see com.dell.coe.pts.technicalservice.TechnologyStackTechnicalService#getAllTechnologyStack()
     */
    @Override
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("/getAllTechnologyStack")
    public List<TechnologyStackVO> getAllTechnologyStack() {
        return technologyStackTechnicalBL.getAllTechnologyStack();
    }

    /* (non-Javadoc)
     * @see com.dell.coe.pts.technicalservice.TechnologyStackTechnicalService#getAllTechnologyStackGroupedByTechnologyCategory()
     */
    @Override
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("/getAllTechnologyStackGroupedByTechnologyCategory")
    public List<TechCategoryReportVO> getAllTechnologyStackGroupedByTechnologyCategory() {
        return technologyStackTechnicalBL.getAllTechnologyStackGroupedByTechnologyCategory();
    }

    /* (non-Javadoc)
     * @see com.dell.coe.pts.technicalservice.TechnologyStackTechnicalService#removeTechnologyStack(com.dell.coe.pts.vo.TechnologyStackVO)
     */
    @Override
    @DELETE
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Path("/removeTechnologyStack")
    public void removeTechnologyStack(@RequestBody TechnologyStackVO technologystack) {
        technologyStackTechnicalBL.removeTechnologyStack(technologystack);
    }
}
