/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.technicalservice;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestBody;

import com.dell.coe.pts.technicalservice.business.TechnologyCategoryTechnicalBL;
import com.dell.coe.pts.vo.TechnologyCategoryVO;
import com.dell.coe.virtuoso.common.service.AbstractServiceImpl;

/**
 * The documentation of the class TechnologyCategoryTechnicalRestServiceImpl.
 *
 * @author 
 * @generated 
 */
@Path("/technologycategory")
public class TechnologyCategoryTechnicalRestServiceImpl extends AbstractServiceImpl implements TechnologyCategoryTechnicalService {

    /** The technology category technical bl. */
    @Autowired
    private TechnologyCategoryTechnicalBL technologyCategoryTechnicalBL;

    /* (non-Javadoc)
     * @see com.dell.coe.pts.technicalservice.TechnologyCategoryTechnicalService#createTechnologyCategory(com.dell.coe.pts.vo.TechnologyCategoryVO)
     */
    @Override
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Path("/createTechnologyCategory")
    public TechnologyCategoryVO createTechnologyCategory(@RequestBody TechnologyCategoryVO technologycategory) {
        return technologyCategoryTechnicalBL.createTechnologyCategory(technologycategory);
    }

    /* (non-Javadoc)
     * @see com.dell.coe.pts.technicalservice.TechnologyCategoryTechnicalService#updateTechnologyCategory(com.dell.coe.pts.vo.TechnologyCategoryVO)
     */
    @Override
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Path("/updateTechnologyCategory")
    public TechnologyCategoryVO updateTechnologyCategory(@RequestBody TechnologyCategoryVO technologycategory) {
        return technologyCategoryTechnicalBL.updateTechnologyCategory(technologycategory);
    }

    /* (non-Javadoc)
     * @see com.dell.coe.pts.technicalservice.TechnologyCategoryTechnicalService#getTechnologyCategoryById(java.lang.Integer)
     */
    @Override
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Path("/getTechnologyCategoryById/{id}")
    public TechnologyCategoryVO getTechnologyCategoryById(@PathParam("id") Integer id) {
        return technologyCategoryTechnicalBL.getTechnologyCategoryById(id);
    }

    /* (non-Javadoc)
     * @see com.dell.coe.pts.technicalservice.TechnologyCategoryTechnicalService#getAllTechnologyCategory()
     */
    @Override
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("/getAllTechnologyCategory")
    public List<TechnologyCategoryVO> getAllTechnologyCategory() {
        return technologyCategoryTechnicalBL.getAllTechnologyCategory();
    }

    /* (non-Javadoc)
     * @see com.dell.coe.pts.technicalservice.TechnologyCategoryTechnicalService#removeTechnologyCategory(com.dell.coe.pts.vo.TechnologyCategoryVO)
     */
    @Override
    @DELETE
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @Path("/removeTechnologyCategory")
    public void removeTechnologyCategory(@RequestBody TechnologyCategoryVO technologycategory) {
        technologyCategoryTechnicalBL.removeTechnologyCategory(technologycategory);
    }
}
