/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service;

import java.util.List;

import com.dell.coe.pts.vo.ProjectTechnologyVO;
import com.dell.coe.pts.vo.ProjectVO;
import com.dell.coe.pts.vo.SearchCriteriaVO;
import com.dell.coe.pts.vo.SearchResultVO;
import com.dell.coe.virtuoso.common.pagination.PagingResponse;
import com.dell.coe.virtuoso.common.service.AbstractService;

/**
 * The documentation of the interface ProjectService.
 *
 * @author 
 * @generated 
 */
public interface ProjectService extends AbstractService {

    /**
     * Find projectby technology list.
     *
     * @param criteriaVOs the criteria v os
     * @param pageNumber the page number
     * @param totalCount the total count
     * @return the paging response
     * @generated 
     */
    PagingResponse<SearchResultVO> findProjectbyTechnologyList(List<SearchCriteriaVO> criteriaVOs, Integer isPagedQuery,
            Integer pageNumber, Integer totalCount);

    /**
     * Retrieve project category distribution.
     *
     * @return the list
     */
    List<ProjectTechnologyVO> retrieveProjectCategoryDistribution();

    /**
     * Retrieve retrieveProjectList .
     *
     * 
     * @return the list
     */
    public List<ProjectVO> retrieveProjectList();

}
