/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service;

import com.dell.coe.pts.vo.SummaryVO;
import com.dell.coe.virtuoso.common.service.AbstractService;

/**
 * The documentation of the interface ProjectService
 * 
 * @author
 * @generated
 */
public interface SummaryService extends AbstractService {

    /**
     * The documentation of the method SummaryVO. * @return
     * 
     * @generated
     */
    SummaryVO retrieveSummary();

}
