/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service;

import java.util.List;

import com.dell.coe.pts.vo.TechnologyStackVO;
import com.dell.coe.virtuoso.common.service.AbstractService;

/**
 * The documentation of the interface TechnologyService.
 *
 * @author 
 * @generated 
 */
public interface TechnologyService extends AbstractService {

    /**
     * Retrieve technology by keyword.
     *
     * @param keyword the keyword
     * @param technologyCatId the technology cat id
     * @return the list
     */
    List<TechnologyStackVO> retrieveTechnologybyKeyword(String keyword, Integer technologyCatId);

    /**
     * Retrieve ordered technology stack.
     *
     * @param technologyCatId the technology cat id
     * @return the list
     */
    List<TechnologyStackVO> retrieveOrderedTechnologyStack(Integer technologyCatId);

    /**
     * Retrieve technology by name and version.
     *
     * @param name the name
     * @param version the version
     * @return the technology stack vo
     */
    TechnologyStackVO retrieveTechnologybyNameandVersion(String name, String version);

    /**
     * Retrieve technology by Name.
     *
     * @param techName the tech name
     * @param technologyCatId the technology cat id
     * @return the list
     */
    List<TechnologyStackVO> retrieveTechnologyVersionbyName(String techName, Integer technologyCatId);

    /**
     * Retrieve retrieveTechnologyStackList .
     *
     * 
     * @return the list
     */
    List<TechnologyStackVO> retrieveTechnologyStackList();
}
