/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service.restImpl;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import com.dell.coe.pts.service.business.ProjectServiceBLImpl;

/**
 * The documentation of the class ProjectServiceTest
 * 
 * @author
 * @generated
 */

public class ProjectServiceTest {

    private ProjectServiceBLImpl projectServiceBLImpl = new ProjectServiceBLImpl();

    /**
     * 
     * @generated
     */
    @Test
    public void retrieveProjectCategoryDistributionTest() {

        // Start of user code for the body of retrieveProjectCategoryDistribution
        // TODO should be implemented
        // any more comments

        // End of user code

    }

    // Start of user code For declaring your own operations for ProjectService
    // add addtional operations here
    // any more comments

    // End of user code
    /**
     * 
     * @generated
     */
    @Test
    public void findProjectbyTechnologyListTest() {

        // Start of user code for the body of findProjectbyTechnologyList
        // TODO should be implemented
        // any more comments

        // End of user code

    }

    // Start of user code For declaring your own operations for ProjectService
    // add addtional operations here
    // any more comments

    // End of user code

    /**
     * The documentation of the method setUpBeforeClass
     */
    @BeforeClass
    public static void setUpBeforeClass() throws Exception {
        // Start of user code for the body of setUpBeforeClass
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method tearDownAfterClass
     */
    @AfterClass
    public static void tearDownAfterClass() throws Exception {
        // Start of user code for the body of tearDownAfterClass
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method setUp
     */
    @Before
    public void setUp() throws Exception {
        // Start of user code for the body of setUp
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method tearDown
     */
    @After
    public void tearDown() throws Exception {
        // Start of user code for the body of tearDown
        // TODO should be implemented
        // any more comments
        // End of user code
    }
}
