/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.technicalservice.business;

import java.util.List;

import com.dell.coe.pts.vo.TechnologyCategoryVO;

/**
 * The documentation of the interface TechnologyCategoryTechnicalBL.
 *
 * @author 
 * @generated 
 */
public interface TechnologyCategoryTechnicalBL {

    /**
     * Creates the technology category.
     *
     * @param technologycategory the technologycategory
     * @return the technology category vo
     */
    TechnologyCategoryVO createTechnologyCategory(TechnologyCategoryVO technologycategory);

    /**
     * Update technology category.
     *
     * @param technologycategory the technologycategory
     * @return the technology category vo
     */
    TechnologyCategoryVO updateTechnologyCategory(TechnologyCategoryVO technologycategory);

    /**
     * Gets the technology category by id.
     *
     * @param id the id
     * @return the technology category by id
     */
    TechnologyCategoryVO getTechnologyCategoryById(Integer id);

    /**
     * Gets the all technology category.
     *
     * @return the all technology category
     */
    List<TechnologyCategoryVO> getAllTechnologyCategory();

    /**
     * Removes the technology category.
     *
     * @param technologycategory the technologycategory
     */
    void removeTechnologyCategory(TechnologyCategoryVO technologycategory);
}
