/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.technicalservice;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import com.dell.coe.pts.technicalservice.business.ProjectTechnicalBLImpl;

/**
 * The documentation of the class ProjectTechnicalRestServiceTest
 * 
 * @author
 * @generated
 */

public class ProjectTechnicalRestServiceTest {

    private static ProjectTechnicalBLImpl projectTechnicalBLImpl = new ProjectTechnicalBLImpl();

    @Test
    public void createProjectTest() {
        // Start of user code for the body of createProjectTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    @Test
    public void updateProjectTest() {
        // Start of user code for the body of updateProjectTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    @Test
    public void getProjectByIdTest() {
        // Start of user code for the body of getProjectByIdTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    @Test
    public void getAllProjectTest() {
        // Start of user code for the body of getAllProjectTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    @Test
    public void removeProjectTest() {
        // Start of user code for the body of removeProjectTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method setUpBeforeClass
     */
    @BeforeClass
    public static void setUpBeforeClass() throws Exception {
        // Start of user code for the body of setUpBeforeClass
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method tearDownAfterClass
     */
    @AfterClass
    public static void tearDownAfterClass() throws Exception {
        // Start of user code for the body of tearDownAfterClass
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method setUp
     */
    @Before
    public void setUp() throws Exception {
        // Start of user code for the body of setUp
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method tearDown
     */
    @After
    public void tearDown() throws Exception {
        // Start of user code for the body of tearDown
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    // Start of user code For declaring your own operations for ProjectTest
    // add addtional operations here
    // any more comments

    // End of user code

}
