/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.technicalservice;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import com.dell.coe.pts.technicalservice.business.TechnologyStackTechnicalBLImpl;

/**
 * The documentation of the class TechnologyStackTechnicalRestServiceTest
 * 
 * @author
 * @generated
 */

public class TechnologyStackTechnicalRestServiceTest {

    private static TechnologyStackTechnicalBLImpl technologyStackTechnicalBLImpl = new TechnologyStackTechnicalBLImpl();

    @Test
    public void createTechnologyStackTest() {
        // Start of user code for the body of createTechnologyStackTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    @Test
    public void updateTechnologyStackTest() {
        // Start of user code for the body of updateTechnologyStackTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    @Test
    public void getTechnologyStackByIdTest() {
        // Start of user code for the body of getTechnologyStackByIdTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    @Test
    public void getAllTechnologyStackTest() {
        // Start of user code for the body of getAllTechnologyStackTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    @Test
    public void removeTechnologyStackTest() {
        // Start of user code for the body of removeTechnologyStackTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method setUpBeforeClass
     */
    @BeforeClass
    public static void setUpBeforeClass() throws Exception {
        // Start of user code for the body of setUpBeforeClass
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method tearDownAfterClass
     */
    @AfterClass
    public static void tearDownAfterClass() throws Exception {
        // Start of user code for the body of tearDownAfterClass
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method setUp
     */
    @Before
    public void setUp() throws Exception {
        // Start of user code for the body of setUp
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method tearDown
     */
    @After
    public void tearDown() throws Exception {
        // Start of user code for the body of tearDown
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    // Start of user code For declaring your own operations for TechnologyStackTest
    // add addtional operations here
    // any more comments

    // End of user code

}
