/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.technicalservice;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

import com.dell.coe.pts.technicalservice.business.TechnologyCategoryTechnicalBLImpl;

/**
 * The documentation of the class TechnologyCategoryTechnicalRestServiceTest
 * 
 * @author
 * @generated
 */

public class TechnologyCategoryTechnicalRestServiceTest {

    private static TechnologyCategoryTechnicalBLImpl technologyCategoryTechnicalBLImpl = new TechnologyCategoryTechnicalBLImpl();

    @Test
    public void createTechnologyCategoryTest() {
        // Start of user code for the body of createTechnologyCategoryTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    @Test
    public void updateTechnologyCategoryTest() {
        // Start of user code for the body of updateTechnologyCategoryTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    @Test
    public void getTechnologyCategoryByIdTest() {
        // Start of user code for the body of getTechnologyCategoryByIdTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    @Test
    public void getAllTechnologyCategoryTest() {
        // Start of user code for the body of getAllTechnologyCategoryTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    @Test
    public void removeTechnologyCategoryTest() {
        // Start of user code for the body of removeTechnologyCategoryTest
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method setUpBeforeClass
     */
    @BeforeClass
    public static void setUpBeforeClass() throws Exception {
        // Start of user code for the body of setUpBeforeClass
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method tearDownAfterClass
     */
    @AfterClass
    public static void tearDownAfterClass() throws Exception {
        // Start of user code for the body of tearDownAfterClass
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method setUp
     */
    @Before
    public void setUp() throws Exception {
        // Start of user code for the body of setUp
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    /**
     * The documentation of the method tearDown
     */
    @After
    public void tearDown() throws Exception {
        // Start of user code for the body of tearDown
        // TODO should be implemented
        // any more comments
        // End of user code
    }

    // Start of user code For declaring your own operations for TechnologyCategoryTest
    // add addtional operations here
    // any more comments

    // End of user code

}
