/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.persistence.dao;

import java.util.List;

import com.dell.coe.pts.common.dao.BaseDao;
import com.dell.coe.pts.persistence.Project;
import com.dell.coe.pts.vo.ProjectVO;

/**
 * The documentation of the class ProjectDao
 * 
 * @author
 * @generated
 */
public interface ProjectDao extends BaseDao<Project> {

    /**
     * Retrieve getAllProjectCount .
     *
     * 
     * @return the Long
     */
    Long getAllProjectCount();

    /**
     * Retrieve getProjectList .
     *
     * 
     * @return the list
     */
    List<ProjectVO> getProjectList();

}
