/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.persistence.dao;

import java.util.List;

import javax.persistence.Query;
import javax.persistence.TypedQuery;

import org.springframework.stereotype.Repository;

import com.dell.coe.pts.common.dao.BaseDaoImpl;
import com.dell.coe.pts.persistence.Project;
import com.dell.coe.pts.vo.ProjectVO;

/**
 * The documentation of the class ProjectDaoImpl.
 *
 * @author 
 * @generated 
 */
@Repository
public class ProjectDaoImpl extends BaseDaoImpl<Project> implements ProjectDao {

    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public ProjectDaoImpl() {
        super(Project.class);
    }

    // Start of user code For declaring your own operations for Project
    // TODO should be implemented
    // any more comments

    /* (non-Javadoc)
     * @see com.dell.coe.pts.persistence.dao.ProjectDao#getAllProjectCount()
     */
    public Long getAllProjectCount() {

        Query query = null;
        StringBuffer createQuery = new StringBuffer();
        createQuery.append("select distinct count(*) from Project");
        query = getEm().createQuery(createQuery.toString());
        return (Long) query.getSingleResult();

    }

    /**
     * Retrieve getProjectList .
     *
     * 
     * @return the list
     */
    public List<ProjectVO> getProjectList() {

        String query = "select new com.dell.coe.pts.vo.ProjectVO(ps.projectId , ps.projName) FROM Project as ps ";
        TypedQuery<ProjectVO> tq = getEm().createQuery(query, ProjectVO.class);
        List<ProjectVO> result = tq.getResultList();

        return result;
    }

    // End of user code

}
