/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.persistence.dao;

import java.util.List;

import com.dell.coe.pts.common.dao.BaseDao;
import com.dell.coe.pts.persistence.TechnologyCategory;
import com.dell.coe.pts.vo.TechnologyCategoryVO;

/**
 * The documentation of the class TechnologyCategoryDao.
 *
 * @author 
 * @generated 
 */
public interface TechnologyCategoryDao extends BaseDao<TechnologyCategory> {

    /**
     * Retrieve technology categoryby name.
     *
     * @param catName the cat name
     * @return the technology category
     */
    TechnologyCategory retrieveTechnologyCategorybyName(String catName);

    /**
     * Gets the all technology category count.
     *
     * @return the all technology category count
     */
    Long getAllTechnologyCategoryCount();

    /**
     * Retrieve getTechnologyCategoryList .
     *
     * 
     * @return the list
     */
    List<TechnologyCategoryVO> getTechnologyCategoryList();
}
