/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.persistence.dao;

import java.util.List;

import javax.persistence.Query;
import javax.persistence.TypedQuery;

import org.springframework.stereotype.Repository;

import com.dell.coe.pts.common.dao.BaseDaoImpl;
import com.dell.coe.pts.persistence.TechnologyCategory;
import com.dell.coe.pts.vo.TechnologyCategoryVO;

/**
 * The documentation of the class TechnologyCategoryDaoImpl.
 *
 * @author 
 * @generated 
 */
@Repository
public class TechnologyCategoryDaoImpl extends BaseDaoImpl<TechnologyCategory> implements TechnologyCategoryDao {

    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public TechnologyCategoryDaoImpl() {
        super(TechnologyCategory.class);
    }

    // Start of user code For declaring your own operations for TechnologyCategory
    // TODO should be implemented
    // any more comments

    /* (non-Javadoc)
     * @see com.dell.coe.pts.persistence.dao.TechnologyCategoryDao#retrieveTechnologyCategorybyName(java.lang.String)
     */
    public TechnologyCategory retrieveTechnologyCategorybyName(String catName) {

        String query = "select technologyCategory from TechnologyCategory technologyCategory where technologyCategory.catName= :catName";
        TypedQuery<TechnologyCategory> tq = getEm().createQuery(query, TechnologyCategory.class);
        tq.setParameter("catName", catName);
        List<TechnologyCategory> result = tq.getResultList();
        if (null != result && 0 < result.size()) {
            return result.get(0);
        }

        return null;

    }

    /* (non-Javadoc)
     * @see com.dell.coe.pts.persistence.dao.TechnologyCategoryDao#getAllTechnologyCategoryCount()
     */
    public Long getAllTechnologyCategoryCount() {

        Query query = null;
        StringBuffer createQuery = new StringBuffer();
        createQuery.append("select distinct count(*) from TechnologyCategory");
        query = getEm().createQuery(createQuery.toString());
        return (Long) query.getSingleResult();

    }

    /**
     * Retrieve getTechnologyCategoryList .
     *
     * 
     * @return the list
     */
    public List<TechnologyCategoryVO> getTechnologyCategoryList() {

        String query = "select new com.dell.coe.pts.vo.TechnologyCategoryVO(tc.technologyCategoryId , tc.catName) FROM TechnologyCategory as tc order by tc.catName asc ";
        TypedQuery<TechnologyCategoryVO> tq = getEm().createQuery(query, TechnologyCategoryVO.class);
        List<TechnologyCategoryVO> result = tq.getResultList();

        return result;
    }
    // End of user code

}
