/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service.business;

import java.util.List;

import com.dell.coe.pts.vo.ProjectTechnologyVO;
import com.dell.coe.pts.vo.ProjectVO;
import com.dell.coe.pts.vo.SearchCriteriaVO;
import com.dell.coe.pts.vo.SearchResultVO;
import com.dell.coe.virtuoso.common.pagination.PagingResponse;

/**
 * The documentation of the interface ProjectServiceBL.
 *
 * @author 
 * @generated 
 */
public interface ProjectServiceBL {

    /**
     * The documentation of the method findProjectbyTechnologyList. 
     *
     * @param criteriaVOs the criteria v os
     * @param pageNumber the page number
     * @param totalCount the total count
     * @return the paging response
     * @generated 
     */
    PagingResponse<SearchResultVO> findProjectbyTechnologyList(List<SearchCriteriaVO> criteriaVOs, Integer isPagedQuery,
            Integer pageNumber, Integer totalCount);

    /**
     * The documentation of the method retrieveProjectCategoryDistribution. 
     *
     * @return the list
     * @generated 
     */
    List<ProjectTechnologyVO> retrieveProjectCategoryDistribution();

    // Start of user code For declaring your own operations for ProjectService
    // add addtional operations here
    // any more comments
    /**
     * Retrieve retrieveProjectList .
     *
     * 
     * @return the list
     */
    List<ProjectVO> retrieveProjectList();
    // End of user code
}
