/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service.business;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.dell.coe.pts.persistence.dao.ProjectDao;
import com.dell.coe.pts.persistence.dao.TechnologyStackDao;
import com.dell.coe.pts.vo.ProjectTechnologyVO;
import com.dell.coe.pts.vo.ProjectVO;
import com.dell.coe.pts.vo.SearchCriteriaVO;
import com.dell.coe.pts.vo.SearchResultVO;
import com.dell.coe.pts.vo.TechnologyStackVO;
import com.dell.coe.virtuoso.common.pagination.PagedData;
import com.dell.coe.virtuoso.common.pagination.PagingResponse;

/**
 * The documentation of the class ProjectServiceBLImpl.
 *
 * @author 
 * @generated 
 */
@Service
public class ProjectServiceBLImpl implements ProjectServiceBL {

    // Start of user code For declaring your own attributes for ProjectService
    // add addtional attributes/fields here
    /** The technology stack dao. */
    // any more comments
    @Autowired
    private TechnologyStackDao technologyStackDao;

    @Autowired
    private ProjectDao projectDao;

    // End of user code
    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public ProjectServiceBLImpl() {
        super();
    }

    /**
     * The documentation of the method retrieveProjectCategoryDistribution.
     *
     * @return the list
     * @generated 
     */
    public List<ProjectTechnologyVO> retrieveProjectCategoryDistribution() {
        // Start of user code for the body of retrieveProjectCategoryDistribution
        // TODO should be implemented
        // any more comments
        Map<String, Integer> projVsTechPercentageMap = new LinkedHashMap<String, Integer>();
        projVsTechPercentageMap.putAll(technologyStackDao.retrieveProjectVsTechnologyData(10));
        List<ProjectTechnologyVO> projectTechnologyVOList = new ArrayList<ProjectTechnologyVO>();
        for (Map.Entry<String, Integer> entry : projVsTechPercentageMap.entrySet()) {
            ProjectTechnologyVO projectTechnologyVO = new ProjectTechnologyVO();
            TechnologyStackVO technologyStackVOobj = new TechnologyStackVO();
            technologyStackVOobj.setTechName(entry.getKey());
            projectTechnologyVO.setProjectCount(entry.getValue());
            projectTechnologyVO.setTechnologyStackVO(technologyStackVOobj);
            projectTechnologyVOList.add(projectTechnologyVO);
        }
        return projectTechnologyVOList;
        // End of user code
    }

    /**
     * The documentation of the method findProjectbyTechnologyList.
     *
     * @param criteriaVOs the criteria value objects
     * @param pageNumber the page number
     * @param totalCount the total count
     * @return the paging response
     * @generated 
     */
    public PagingResponse<SearchResultVO> findProjectbyTechnologyList(List<SearchCriteriaVO> criteriaVOs, Integer isPagedQuery,
            Integer pageNumber, Integer totalCount) {
        // Start of user code for the body of findProjectbyTechnologyList
        // TODO should be implemented
        // any more comments

        PagingResponse<SearchResultVO> pagedSearchResultVO = new PagingResponse<SearchResultVO>();
        Boolean isPaged;
        if (null != isPagedQuery) {
            isPaged = (isPagedQuery == 1) ? true : false;
        } else {
            isPaged = false;
        }
        List<SearchResultVO> resultList = new ArrayList<SearchResultVO>();
        resultList.add(technologyStackDao.executeSearchCriteria(criteriaVOs, isPaged, totalCount, pageNumber));

        pagedSearchResultVO.setWrappedList(resultList);
        PagedData pg = new PagedData();
        pg.setPage(pageNumber);
        pg.setPageSize(10);
        pg.setTotalItems(resultList.get(0).getTotalCount());
        pagedSearchResultVO.setPageData(pg);
        return pagedSearchResultVO;

        //return null;
        // End of user code
    }
    // Start of user code For declaring your own operations for ProjectService
    // add addtional operations here
    // any more comments

    /**
     * Retrieve retrieveProjectList .
     *
     * 
     * @return the list
     */
    public List<ProjectVO> retrieveProjectList() {
        return projectDao.getProjectList();
    }
    // End of user code
    // Start of user code For declaring your own accessors for ProjectService
    // add addtional accessors here
    // any more comments

    public TechnologyStackDao getTechnologyStackDao() {
        return technologyStackDao;
    }

    public void setTechnologyStackDao(TechnologyStackDao technologyStackDao) {
        this.technologyStackDao = technologyStackDao;
    }

    public ProjectDao getProjectDao() {
        return projectDao;
    }

    public void setProjectDao(ProjectDao projectDao) {
        this.projectDao = projectDao;
    }

    // End of user code
}
