/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service.business;

import com.dell.coe.pts.vo.SummaryVO;

/**
 * The documentation of the interface ProjectServiceBL.
 *
 * @author 
 * @generated 
 */
public interface SummaryServiceBL {

    /**
     * The documentation of the method findProjectbyTechnologyList. * @param technologyList
     *
     * @return the summary vo
     * @generated 
     */
    SummaryVO retrieveSummary();
}
