/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service.business;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.dell.coe.pts.persistence.dao.ProjectDao;
import com.dell.coe.pts.persistence.dao.TechnologyCategoryDao;
import com.dell.coe.pts.persistence.dao.TechnologyStackDao;
import com.dell.coe.pts.vo.SummaryVO;

/**
 * The documentation of the class ProjectServiceBLImpl.
 *
 * @author 
 * @generated 
 */
@Service
public class SummaryServiceBLImpl implements SummaryServiceBL {

    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public SummaryServiceBLImpl() {
        super();
    }

    /** The project dao. */
    @Autowired
    private ProjectDao projectDao;

    /** The technology category dao. */
    @Autowired
    private TechnologyCategoryDao technologyCategoryDao;

    /** The technology stack dao. */
    @Autowired
    private TechnologyStackDao technologyStackDao;

    /* (non-Javadoc)
     * @see com.dell.coe.pts.service.business.SummaryServiceBL#retrieveSummary()
     */
    @Override
    public SummaryVO retrieveSummary() {
        SummaryVO summaryVO = new SummaryVO();
        summaryVO.setTotalProjects(projectDao.getAllProjectCount());
        summaryVO.setTotalTechnologies(technologyStackDao.getAllTechnologyStackCount());
        summaryVO.setTotalTechnologyCategories(technologyCategoryDao.getAllTechnologyCategoryCount());
        //projectDao.getAllProjectCount();
        return summaryVO;
    }

    /**
     * Gets the project dao.
     *
     * @return the project dao
     */
    public ProjectDao getProjectDao() {
        return projectDao;
    }

    /**
     * Sets the project dao.
     *
     * @param projectDao the new project dao
     */
    public void setProjectDao(ProjectDao projectDao) {
        this.projectDao = projectDao;
    }

    /**
     * Gets the technology category dao.
     *
     * @return the technology category dao
     */
    public TechnologyCategoryDao getTechnologyCategoryDao() {
        return technologyCategoryDao;
    }

    /**
     * Sets the technology category dao.
     *
     * @param technologyCategoryDao the new technology category dao
     */
    public void setTechnologyCategoryDao(TechnologyCategoryDao technologyCategoryDao) {
        this.technologyCategoryDao = technologyCategoryDao;
    }

    /**
     * Gets the technology stack dao.
     *
     * @return the technology stack dao
     */
    public TechnologyStackDao getTechnologyStackDao() {
        return technologyStackDao;
    }

    /**
     * Sets the technology stack dao.
     *
     * @param technologyStackDao the new technology stack dao
     */
    public void setTechnologyStackDao(TechnologyStackDao technologyStackDao) {
        this.technologyStackDao = technologyStackDao;
    }

}
