/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service.business;

import java.util.HashSet;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.dell.coe.pts.persistence.Project;
import com.dell.coe.pts.persistence.TechnologyStack;
import com.dell.coe.pts.persistence.dao.TechnologyStackDao;
import com.dell.coe.pts.util.ConversionUtil;
import com.dell.coe.pts.vo.TechnologyStackVO;

/**
 * The documentation of the class TechnologyServiceBLImpl.
 *
 * @author 
 * @generated 
 */
@Service
public class TechnologyServiceBLImpl implements TechnologyServiceBL {

    // Start of user code For declaring your own attributes for TechnologyService
    // add addtional attributes/fields here
    // any more comments

    /** The technology stack dao. */
    @Autowired
    TechnologyStackDao technologyStackDao;

    // End of user code
    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public TechnologyServiceBLImpl() {
        super();
    }

    /**
     * The documentation of the method retrieveTechnologybyKeyword.
     *
     * @param keyword the keyword
     * @param technologyCatId the technology cat id
     * @return the list
     * @generated 
     */
    /**
     * 
     */
    public List<TechnologyStackVO> retrieveTechnologybyKeyword(String keyword, Integer technologyCatId) {
        // Start of user code for the body of retrieveTechnologybyKeyword
        // TODO should be implemented
        // any more comments
        List<TechnologyStack> technologyStackList = technologyStackDao.retrieveTechnologybyKeyword(keyword, technologyCatId);
        List<TechnologyStackVO> technologyStackVOList = ConversionUtil.convertListToTechnologyStackVOList(technologyStackList, true, true);
        return technologyStackVOList;
        // End of user code
    }
    // Start of user code For declaring your own operations for TechnologyService
    // add addtional operations here
    // any more comments

    public TechnologyStackVO retrieveTechnologybyNameandVersion(String name, String version) {
        TechnologyStack technologyStackObj = technologyStackDao.retrieveTechnologybyNameandVersion(name, version);
        if (null != technologyStackObj) {
            technologyStackObj.setProject(new HashSet<Project>());
        }
        TechnologyStackVO technologyStackVOObj = ConversionUtil.convertToTechnologyStackVo(technologyStackObj, true, true);
        return technologyStackVOObj;
    }

    /**
     * Retrieve technologyby Name.
     *
     * @param keyword the technology Name
     * @param technologyCatId the technology cat id
     * @return the list
     */
    public List<TechnologyStackVO> retrieveTechVersionbyTechName(String techName, Integer technologyCatId) {
        // Start of user code for the body of retrieveTechVersionbyTechName
        // TODO should be implemented
        // any more comments
        List<TechnologyStack> technologyStackList = technologyStackDao.retrieveTechnologybyName(techName, technologyCatId);
        List<TechnologyStackVO> technologyStackVOList = ConversionUtil.convertListToTechnologyStackVOList(technologyStackList, true, true);
        return technologyStackVOList;
        // End of user code
    }
    // End of user code
    // Start of user code For declaring your own accessors for TechnologyService
    // add addtional accessors here
    // any more comments

    /**
     * Retrieve retrieveTechnologyStackList .
     *
     * 
     * @return the list
     */
    public List<TechnologyStackVO> retrieveTechnologyStackList() {
        return technologyStackDao.getTechnologyStackList();
    }

    // End of user code

    public List<TechnologyStackVO> retrieveOrderedTechnologyStack(Integer technologyCatId) {
        List<TechnologyStack> technologyStackList = technologyStackDao.retrieveOrderedTechnologyStack(technologyCatId);
        List<TechnologyStackVO> technologyStackVOList = ConversionUtil
                .convertListToTechnologyStackVOList(technologyStackList, false, false);
        return technologyStackVOList;
    }
}
