/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service.business;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.dell.coe.pts.persistence.TechnologyCategory;
import com.dell.coe.pts.persistence.dao.TechnologyCategoryDao;
import com.dell.coe.pts.persistence.dao.TechnologyStackDao;
import com.dell.coe.pts.util.ConversionUtil;
import com.dell.coe.pts.vo.ProjectTechCategoryVO;
import com.dell.coe.pts.vo.TechnologyCategoryVO;

/**
 * The documentation of the class TechnologyCategoryServiceBLImpl.
 *
 * @author 
 * @generated 
 */
@Service
public class TechnologyCategoryServiceBLImpl implements TechnologyCategoryServiceBL {

    // Start of user code For declaring your own attributes for TechnologyCategoryService
    // add addtional attributes/fields here
    /** The technology category dao. */
    @Autowired
    private TechnologyCategoryDao technologyCategoryDao;

    /** The technology stack dao. */
    @Autowired
    private TechnologyStackDao technologyStackDao;

    // End of user code
    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public TechnologyCategoryServiceBLImpl() {
        super();
    }

    /**
     * The documentation of the method retrieveTechnologyCategorybyName.
     *
     * @param categoryName the category name
     * @return the technology category vo
     * @generated 
     */
    public TechnologyCategoryVO retrieveTechnologyCategorybyName(String categoryName) {
        // Start of user code for the body of retrieveTechnologyCategorybyName
        // TODO should be implemented
        // any more comments
        TechnologyCategory technologyCategoryOutputObj = technologyCategoryDao.retrieveTechnologyCategorybyName(categoryName);
        return ConversionUtil.convertToTechnologyCategoryVO(technologyCategoryOutputObj);
        //return null;

        // End of user code
    }

    /**
     * The documentation of the method retrieveTechnologyCategoryDistribution.
     *
     * @return the list
     * @generated 
     */
    public List<ProjectTechCategoryVO> retrieveTechnologyCategoryDistribution() {
        // Start of user code for the body of retrieveTechnologyCategoryDistribution
        // TODO should be implemented
        // any more comments

        Map<String, Integer> projVsCatMap = new LinkedHashMap<String, Integer>();
        projVsCatMap.putAll(technologyStackDao.retrieveProjectVsCategoryData(10));
        List<ProjectTechCategoryVO> projTechCatVOList = new ArrayList<ProjectTechCategoryVO>();

        for (Map.Entry<String, Integer> entry : projVsCatMap.entrySet()) {
            ProjectTechCategoryVO projTechCatVO = new ProjectTechCategoryVO();
            TechnologyCategoryVO techCatVOobj = new TechnologyCategoryVO();
            TechnologyCategory techCatobj = technologyCategoryDao.retrieveTechnologyCategorybyName(entry.getKey());
            techCatVOobj = ConversionUtil.convertToTechnologyCategoryVO(techCatobj);
            projTechCatVO.setTechnologyCategoryVO(techCatVOobj);
            projTechCatVO.setProjectCount(entry.getValue().doubleValue());
            projTechCatVOList.add(projTechCatVO);
        }
        return projTechCatVOList;
        // End of user code
    }
    // Start of user code For declaring your own operations for TechnologyCategoryService
    // add addtional operations here
    // any more comments

    /**
     * Retrieve retrieveTechnologyCategoryList .
     *
     * 
     * @return the list
     */
    public List<TechnologyCategoryVO> retrieveTechnologyCategoryList() {
        return technologyCategoryDao.getTechnologyCategoryList();
    }

    /**
     * Gets the technology category dao.
     *
     * @return the technology category dao
     */
    public TechnologyCategoryDao getTechnologyCategoryDao() {
        return technologyCategoryDao;
    }

    /**
     * Sets the technology category dao.
     *
     * @param technologyCategoryDao the new technology category dao
     */
    public void setTechnologyCategoryDao(TechnologyCategoryDao technologyCategoryDao) {
        this.technologyCategoryDao = technologyCategoryDao;
    }

    /**
     * Gets the technology stack dao.
     *
     * @return the technology stack dao
     */
    public TechnologyStackDao getTechnologyStackDao() {
        return technologyStackDao;
    }

    /**
     * Sets the technology stack dao.
     *
     * @param technologyStackDao the new technology stack dao
     */
    public void setTechnologyStackDao(TechnologyStackDao technologyStackDao) {
        this.technologyStackDao = technologyStackDao;
    }

    // End of user code
    // Start of user code For declaring your own accessors for TechnologyCategoryService
    // add addtional accessors here
    // any more comments

    // End of user code
}
