/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service.business;

import java.util.List;

import com.dell.coe.pts.vo.ProjectTechCategoryVO;
import com.dell.coe.pts.vo.TechnologyCategoryVO;

/**
 * The documentation of the interface TechnologyCategoryServiceBL.
 *
 * @author 
 * @generated 
 */
public interface TechnologyCategoryServiceBL {

    /**
     * The documentation of the method retrieveTechnologyCategorybyName. * @param categoryName
     *
     * @param categoryName the category name
     * @return the technology category vo
     * @generated 
     */
    TechnologyCategoryVO retrieveTechnologyCategorybyName(String categoryName);

    /**
     * The documentation of the method retrieveTechnologyCategoryDistribution. * @return
     *
     * @return the list
     * @generated 
     */
    List<ProjectTechCategoryVO> retrieveTechnologyCategoryDistribution();

    // Start of user code For declaring your own operations for TechnologyCategoryService
    // add addtional operations here
    // any more comments

    /**
     * Retrieve retrieveTechnologyCategoryList .
     *
     * 
     * @return the list
     */
    List<TechnologyCategoryVO> retrieveTechnologyCategoryList();
    // End of user code
}
