/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service.restImpl;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.springframework.beans.factory.annotation.Autowired;

import com.dell.coe.pts.service.SummaryService;
import com.dell.coe.pts.service.business.SummaryServiceBL;
import com.dell.coe.pts.vo.SummaryVO;
import com.dell.coe.virtuoso.common.service.AbstractServiceImpl;

/**
 * The documentation of the class ProjectServiceImpl.
 *
 * @author 
 * @generated 
 */
@Path("/summaryService")
public class SummaryServiceImpl extends AbstractServiceImpl implements SummaryService {

    /** The summary service bl. */
    @Autowired
    private SummaryServiceBL summaryServiceBL;

    /**
     * Gets the summary service bl.
     *
     * @return the summary service bl
     */
    public SummaryServiceBL getSummaryServiceBL() {
        return summaryServiceBL;
    }

    /**
     * Sets the summary service bl.
     *
     * @param summaryServiceBL the new summary service bl
     */
    public void setSummaryServiceBL(SummaryServiceBL summaryServiceBL) {
        this.summaryServiceBL = summaryServiceBL;
    }

    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public SummaryServiceImpl() {
        super();
    }

    /**
     * The documentation of the method retrieveSummary. * @return
     *
     * @return the summary vo
     * @generated 
     */
    @GET
    @Path("/retrieveSummary")
    @Produces(MediaType.APPLICATION_JSON)
    public SummaryVO retrieveSummary() {
        return summaryServiceBL.retrieveSummary();
    }

}
