/**
 * Generated by Dell Virtuoso
 * All rights reserved.
 */
package com.dell.coe.pts.service.restImpl;

import java.util.List;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;

import org.springframework.beans.factory.annotation.Autowired;

import com.dell.coe.pts.service.TechnologyService;
import com.dell.coe.pts.service.business.TechnologyServiceBL;
import com.dell.coe.pts.vo.TechnologyStackVO;
import com.dell.coe.virtuoso.common.service.AbstractServiceImpl;

/**
 * The documentation of the class TechnologyServiceImpl.
 *
 * @author 
 * @generated 
 */
@Path("/technologyService")
public class TechnologyServiceImpl extends AbstractServiceImpl implements TechnologyService {

    /** The technology service bl. */
    @Autowired
    private TechnologyServiceBL technologyServiceBL;

    /**
     * The documentation of the constructor.
     * 
     * @generated
     */
    public TechnologyServiceImpl() {
        super();
    }

    /**
     * The documentation of the method retrieveTechnologybyKeyword. * @param keyword
     *
     * @param keyword the keyword
     * @param technologyCatId the technology cat id
     * @return the list
     * @generated 
     */
    @GET
    @Path("/retrieveTechnologybyKeyword/{keyword}")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public List<TechnologyStackVO> retrieveTechnologybyKeyword(@PathParam("keyword") String keyword,
            @QueryParam("technologyCatId") Integer technologyCatId) {
        return technologyServiceBL.retrieveTechnologybyKeyword(keyword, technologyCatId);
    }

    @GET
    @Path("/retrieveOrderedTechnologyStack")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public List<TechnologyStackVO> retrieveOrderedTechnologyStack(@QueryParam("technologyCatId") Integer technologyCatId) {
        return technologyServiceBL.retrieveOrderedTechnologyStack(technologyCatId);
    }

    @GET
    @Path("/retrieveTechnologybyNameandVersion/{name}/{version}")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public TechnologyStackVO retrieveTechnologybyNameandVersion(@PathParam("name") String name, @PathParam("version") String version) {
        return technologyServiceBL.retrieveTechnologybyNameandVersion(name, version);

    }

    /**
     * Retrieve technologyby Name.
     *
     * @param keyword the technology Name
     * @param technologyCatId the technology cat id
     * @return the list
     */
    @GET
    @Path("/retrieveTechnologyVersionbyName/{techName}")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public List<TechnologyStackVO> retrieveTechnologyVersionbyName(@PathParam("techName") String techName,
            @QueryParam("technologyCatId") Integer technologyCatId) {
        return technologyServiceBL.retrieveTechVersionbyTechName(techName, technologyCatId);
    }

    /**
     * Retrieve retrieveTechnologyStackList .
     *
     * 
     * @return the list
     */
    @GET
    @Path("/retrieveTechnologyStackList")
    @Produces(MediaType.APPLICATION_JSON)
    public List<TechnologyStackVO> retrieveTechnologyStackList() {
        return technologyServiceBL.retrieveTechnologyStackList();
    }

    /**
     * The documentation of the getter getTechnologyServiceBL.
     *
     * @return the technology service bl
     * @generated 
     */
    public TechnologyServiceBL getTechnologyServiceBL() {
        return technologyServiceBL;
    }

    /**
     * The documentation of the setter setTechnologyServiceBL.
     *
     * @param technologyServiceBL the new technology service bl
     * @generated 
     */
    public void setTechnologyServiceBL(TechnologyServiceBL technologyServiceBL) {
        this.technologyServiceBL = technologyServiceBL;
    }
}
